import "./styles/resetStyles.css";
import "./styles/global.css";
import styles from "./styles/app.module.css";

import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Header />
        <main className={styles.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
