import "./styles/resetStyles.css";
import "./styles/global.css";
import "./styles/app.css";
import Link from "next/link";
import { Header } from "@/widgets/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Link href="/film">Фильм</Link>
        <Link href="/">Главная</Link>
        {children}
        <footer>FOOTER</footer>
      </body>
    </html>
  );
}
